apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhenaapp
  labels:
    app: rhenaapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rhenaapp
  template:
    metadata:
      labels:
        app: rhenaapp
    spec:
      containers:
        - name: rhenaapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rhenaapp-port
              containerPort: 8080
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;
        - name: init-memcache
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;
